name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
      # to compile with cl.exe on windows https://github.com/marketplace/actions/enable-developer-command-prompt
      - uses: ilammy/msvc-dev-cmd@v1
      # used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        env:
          #CIBW_BEFORE_ALL: python -m pip install numpy
          #CIBW_TEST_REQUIRES: numpy
        run: python -m cibuildwheel --output-dir wheelhouse


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl